server:
  port: 8080

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}
    listener:
      simple:
        acknowledge-mode: manual

ship:
  queue: ${SHIP_QUEUE:ship-order}

consumer:
  concurrency: ${CONSUMER_CONCURRENCY:8}
