server:
  port: 8081

cca:
  base-url: http://localhost:8080

ship:
  queue: ship-order

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
